const createSqliteModel = require("./createSqliteModel");
const {
  asInteger,
  asString,
  asStringArray,
  normalizeAddress,
  normalizeFooterLinks,
  normalizeHero,
  normalizeMetrics,
  normalizeSectionToggles,
  normalizeSeo,
  normalizeSocial,
  normalizeValues,
} = require("./shared");

module.exports = createSqliteModel({
  tableName: "site_settings",
  columns: {
    singletonKey: "TEXT",
    companyName: "TEXT",
    legalName: "TEXT",
    tagline: "TEXT",
    description: "TEXT",
    website: "TEXT",
    phone: "TEXT",
    phoneRaw: "TEXT",
    email: "TEXT",
    workingHours: "TEXT",
    yearFounded: "INTEGER",
    aboutHeadline: "TEXT",
    aboutDescription: "TEXT",
  },
  uniqueFields: ["singletonKey"],
  indexFields: ["singletonKey"],
  normalize(payload = {}) {
    return {
      singletonKey: asString(payload.singletonKey, "main-site-settings"),
      companyName: asString(payload.companyName),
      legalName: asString(payload.legalName),
      tagline: asString(payload.tagline),
      description: asString(payload.description),
      website: asString(payload.website),
      phone: asString(payload.phone),
      phoneRaw: asString(payload.phoneRaw),
      email: asString(payload.email),
      workingHours: asString(payload.workingHours),
      yearFounded: asInteger(payload.yearFounded, 2019),
      address: normalizeAddress(payload.address),
      social: normalizeSocial(payload.social),
      hero: normalizeHero(payload.hero),
      stats: normalizeMetrics(payload.stats),
      aboutHeadline: asString(payload.aboutHeadline),
      aboutDescription: asString(payload.aboutDescription),
      aboutStory: asStringArray(payload.aboutStory),
      whyChooseUs: asStringArray(payload.whyChooseUs),
      values: normalizeValues(payload.values),
      footerLinks: normalizeFooterLinks(payload.footerLinks),
      seoDefaults: normalizeSeo(payload.seoDefaults),
      sectionToggles: normalizeSectionToggles(payload.sectionToggles),
    };
  },
});
